// Automatically generated by astro-icon
// 2a7f43eff1ad97c31e9108a584ae9f441182b1c4ae71ea8c4e37996d8bdd55ac

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "mdi:arrow-left"
		| "mdi:home"
		| "mdi:email"
		| "mdi:github"
		| "mdi:linkedin"
		| "mdi:codepen"
		| "mdi:download"
		| "mdi:file-document"
		| "mdi:file-pdf-box"
		| "mdi:open-in-new"
		| "mdi:eye"
		| "mdi:text-box"
		| "mdi:xml"
		| "mdi:watch-variant";
}