// Automatically generated by astro-icon
// f7105e578a8a40ef3374e4739057f8076e84ada352add421d14d51750fd027ab

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "mdi:arrow-left"
		| "mdi:home"
		| "mdi:email"
		| "mdi:github"
		| "mdi:linkedin"
		| "mdi:codepen"
		| "mdi:download"
		| "mdi:file-document"
		| "mdi:file-pdf-box"
		| "mdi:open-in-new"
		| "mdi:eye"
		| "mdi:text-box"
		| "mdi:xml"
		| "mdi:watch-variant"
		| "mdi:check-decagram";
}