// Automatically generated by astro-icon
// 9581403529d6f53f8dc69c4474ca7c3836b59819d37dc7382dfea91801c729e3

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "mdi:arrow-left"
		| "mdi:email"
		| "mdi:github"
		| "mdi:linkedin"
		| "mdi:codepen"
		| "mdi:download"
		| "mdi:file-document"
		| "mdi:file-pdf-box"
		| "mdi:open-in-new";
}